"""Fonte única do conteúdo da campanha Plantão Piercing.

Gera src/campanha.json, que alimenta o renderizador de capas (capas.html)
e a página do plano (build_pagina.py).

Marcação nos títulos: *texto* = vermelho, [texto] = caixa vermelha.
"""
import json, os

CTA_PADRAO = "Curso de Body Piercing para iniciantes e profissionais. R$250 ou 12x. Link na bio."

CARROSSEIS = [
    {
        "id": "c01", "data": "08/10", "dia": "qui", "nome": "A briga dos R$120",
        "publico": "Ambos", "impulsionar": False,
        "nota_impulso": "Só orgânico. Tema eleitoral com foto de candidato: não impulsione, cite os dois lados e troque “reprodução” pelo crédito real da foto.",
        "layout": "manchete", "foto": "lula-pb",
        "tag": "PLANTÃO", "topico": "ELEIÇÕES 2026 · SALÁRIO MÍNIMO",
        "head": "LULA E FLÁVIO BRIGAM POR *R$120* NO SALÁRIO MÍNIMO. UM PIERCER COBRA ISSO [NUM FURO.*]",
        "sub": "R$120 é o aumento proposto pra 2027. *Preço de exemplo; varia por cidade.",
        "fonte": "PLOA 2027: R$1.621 → R$1.741 · FOTO: REPRODUÇÃO",
        "slides": [
            "Capa.",
            "A briga do 2º turno chegou no seu bolso. O assunto da semana é o *salário mínimo.*",
            "Lula acusa a campanha de Flávio de querer *desvincular as aposentadorias* do mínimo. Flávio chama de fake news e promete *preservar o valor* do piso.",
            "O número oficial: o projeto de orçamento leva o mínimo de R$1.621 para *R$1.741 em 2027.* São R$120 a mais. E ainda pode mudar em dezembro.",
            "Este post não é sobre em quem votar. É sobre quanto R$120 vale *na sua mão.*",
            "Num estúdio, R$120 é *um furo.* (Exemplo: o preço muda por cidade; fontes do setor citam de R$40 a R$240 por furo.)",
            "Um furo por dia, 20 dias no mês: *R$2.400 de faturamento.* Antes de joia, material, impostos e alvará.",
            "O aumento do mínimo vem uma vez por ano, se vier. *O próximo cliente pode vir amanhã.*",
            "Iniciante: aprende do zero, com biossegurança. Profissional: aprende a *cobrar mais de R$120.*",
            CTA_PADRAO,
        ],
        "legenda": "Lula e Flávio estão brigando pelo salário mínimo. O aumento proposto pra 2027 é de R$120.\n\nNum estúdio de piercing, R$120 é um furo.\n\nQuem ganhar no domingo, a sua renda não precisa esperar Brasília. Curso de Body Piercing no link da bio.\n\n(Valores de exemplo; o preço do furo varia na sua cidade.)",
        "fontes": [
            {"t": "A Revista: Lula x Flávio, o que pode mudar no salário mínimo e na aposentadoria", "u": "https://arevista.com.br/economia/lula-x-flavio-o-que-pode-mudar-na-aposentadoria-no-bpc-e-no-salario-minimo-apos-a-eleicao/"},
            {"t": "SBT News: Flávio Bolsonaro promete preservar valor do salário mínimo", "u": "https://sbtnews.sbt.com.br/noticia/eleicoes/flavio-bolsonaro-promete-preservar-valor-do-salario-minimo"},
            {"t": "CNN Brasil: Flávio diz que mudar salário mínimo é fake news de campanha", "u": "https://www.cnnbrasil.com.br/eleicoes/a-cnn-flavio-diz-que-mudar-salario-minimo-e-fake-news-de-campanha/"},
            {"t": "Itatiaia: salário mínimo 2027, proposta de R$1.741", "u": "https://www.itatiaia.com.br/economia/salario-minimo-2027-proposta-r-1741/"},
        ],
    },
    {
        "id": "c02", "data": "10/10", "dia": "sáb", "nome": "A fila do primeiro brinco",
        "publico": "Profissional", "impulsionar": True,
        "nota_impulso": "Pode impulsionar para público adulto (pais e piercers). Sem foto de bebê no anúncio.",
        "layout": "foto", "foto": "piercer-noir",
        "tag": "12/10", "topico": "DIA DAS CRIANÇAS",
        "head": "A FILA DO *PRIMEIRO BRINCO* ESTÁ NA FARMÁCIA. DEVIA ESTAR NO [SEU ESTÚDIO.]",
        "sub": "O que a Anvisa permite, o que os pediatras orientam e onde o piercer entra.",
        "fonte": "Anvisa RDC 44/2009 · SBP · CFF",
        "slides": [
            "Capa.",
            "Feriado de 12/10: fila na farmácia pro primeiro brinco. É permitido. A RDC 44/2009 da Anvisa autoriza farmácia a perfurar o lóbulo com aparelho próprio e registrado.",
            "Mas em 2025 o próprio Conselho Federal de Farmácia propôs atualizar a regra, citando que a pressão da pistola tradicional assusta crianças e adultos.",
            "O tema voltou em agosto: a médica e ex-BBB Laís Caldas contou que a filha nasceu com lóbulo bífido.",
            "O que pediatras costumam orientar: esperar pelo menos 2 meses de vida, depois das primeiras vacinas. Muitos preferem depois dos 6 meses.",
            "Onde o piercer entra: avaliação do lóbulo, marcação simétrica, técnica, joia adequada e orientação clara pros pais.",
            "Regras do jogo: autorização e presença dos responsáveis, alvará sanitário em dia e a lei do seu estado e município para menores.",
            "Furo infantil feito com calma e técnica é um nicho que fica com quem se preparou. (Use este slide só se o curso tiver essa aula.)",
            CTA_PADRAO,
        ],
        "legenda": "Segunda é Dia das Crianças e a fila do primeiro brinco vai pra farmácia.\n\nÉ permitido. Mas existe outro jeito de fazer, e quem domina esse atendimento ganha a confiança da família inteira.\n\nO que a Anvisa permite e o que os pediatras orientam está no carrossel.",
        "fontes": [
            {"t": "CFF: farmacêuticos propõem norma para furo humanizado (2025)", "u": "https://site.cff.org.br/noticia/noticias-do-cff/28/07/2025/farmaceuticos-propoem-norma-para-furo-na-orelha-com-foco-em-atendimento-humanizado"},
            {"t": "SBP: furar ou não a orelha do bebê", "u": "https://www.sbp.com.br/furar-ou-nao-a-orelha-do-bebe-saiba-o-que-e-permitido/"},
            {"t": "Estado de Minas: idade ideal para furar a orelha do bebê (ago/2026)", "u": "https://www.em.com.br/bem-viver/2026/08/7475865-qual-a-idade-ideal-para-furar-a-orelha-do-bebe.html"},
        ],
    },
    {
        "id": "c03", "data": "14/10", "dia": "qua", "nome": "Ganchos em Joinville",
        "publico": "Iniciante", "impulsionar": True,
        "nota_impulso": "Pode impulsionar. Sem foto de suspensão no anúncio (Meta barra imagem chocante).",
        "layout": "foto", "foto": "piercer-sangue",
        "tag": "ESTE FIM DE SEMANA", "topico": "TATTOO SHOW JOINVILLE · 16–18/10",
        "head": "TEM GENTE SENDO *PENDURADA POR GANCHOS* EM JOINVILLE. E VOCÊ COM MEDO DE FURAR UM [LÓBULO?]",
        "sub": "Medo não é falta de coragem. É falta de método.",
        "fonte": "ND+ · programação Tattoo Show Joinville 2026",
        "slides": [
            "Capa.",
            "De 16 a 18 de outubro, a 11ª Tattoo Show Joinville tem show de suspensão corporal e um espaço só de piercing.",
            "Suspensão é o corpo sustentado por ganchos que atravessam a pele. Só acontece com equipe treinada e protocolo rígido.",
            "O que torna isso possível não é coragem. É método, anatomia e biossegurança.",
            "Agora você: com medo de furar um lóbulo. É o mesmo medo, só que sem método.",
            "Os 3 medos de quem começa: machucar o cliente, causar infecção, errar a posição.",
            "Cada um tem resposta técnica: anatomia e marcação; protocolo de esterilização e descarte; joia e calibre certos.",
            "O curso começa exatamente por esses três pontos.",
            CTA_PADRAO,
        ],
        "legenda": "Esse fim de semana tem gente sendo suspensa por ganchos em Joinville.\n\nE tem gente que sonha em ser piercer mas trava no primeiro lóbulo.\n\nO medo some quando o método aparece. Curso no link da bio.",
        "fontes": [
            {"t": "ND+: Tattoo Show Joinville 2026, programação", "u": "https://ndmais.com.br/cultura/tattoo-show-joinville-2026-programacao-shows-atracoes"},
        ],
    },
    {
        "id": "c04", "data": "19/10", "dia": "seg", "nome": "Instagram virou pago",
        "publico": "Profissional", "impulsionar": True,
        "nota_impulso": "Pode impulsionar. Não use logo do Instagram no criativo do anúncio.",
        "layout": "tipo", "big": "R$10<small>/mês</small>",
        "tag": "PLANTÃO", "topico": "META · INSTAGRAM PLUS",
        "head": "É O QUE O INSTAGRAM COBRA PRO SEU STORY *APARECER PRIMEIRO.* CLIENTE BEM ATENDIDO TE DIVULGA [DE GRAÇA.]",
        "sub": "Alcance se compra. Indicação se conquista no furo.",
        "fonte": "Meta · Instagram Plus no Brasil, jun/2026",
        "slides": [
            "Capa.",
            "Desde junho existe o Instagram Plus no Brasil: R$10 por mês. Inclui story com prioridade de entrega, story de 48h e até 6 posts fixados.",
            "A versão gratuita continua. Mas o recado é claro: alcance virou produto.",
            "Estúdio que depende só de alcance vai pagar cada vez mais pra ser visto.",
            "Estúdio que vive de indicação paga menos: o cliente cicatrizou bem, mostrou pra amiga, a amiga marcou horário.",
            "Indicação nasce em 3 momentos: o atendimento, a cicatrização e o pós-cuidado que você ensina.",
            "Cicatrização ruim também viraliza. Cada furo inflamado é um story falando mal de você.",
            "No curso: protocolo de pós-cuidado, joia certa pra cada região e como transformar cliente em indicação.",
            CTA_PADRAO,
        ],
        "legenda": "O Instagram agora cobra R$10/mês pro seu story aparecer primeiro.\n\nTem estúdio que vai pagar. Tem estúdio que nem precisa: o cliente cicatriza bem e faz a propaganda sozinho.\n\nDe que lado você quer estar?",
        "fontes": [
            {"t": "Jornal Opção: Instagram passa a ter assinatura paga no Brasil", "u": "https://www.jornalopcao.com.br/tecnologia/instagram-passa-a-ter-assinatura-paga-no-brasil-entenda-o-que-muda-833913/"},
            {"t": "Meio & Mensagem: Meta lança assinatura premium do Instagram no Brasil", "u": "https://www.meioemensagem.com.br/midia/meta-lanca-assinatura-premium-do-instagram-no-brasil"},
        ],
    },
    {
        "id": "c05", "data": "23/10", "dia": "sex", "nome": "Domingo, 25",
        "publico": "Ambos", "impulsionar": False,
        "nota_impulso": "Cita eleição: só orgânico. Nunca tome lado.",
        "layout": "tipo", "big": "25/10",
        "tag": "2º TURNO", "topico": "ELEIÇÕES 2026",
        "head": "QUEM GANHAR NO DOMINGO *NÃO VAI PAGAR* OS SEUS [BOLETOS DE NOVEMBRO.]",
        "sub": "Seja qual for o resultado, a sua renda continua sendo problema seu.",
        "fonte": "TSE · calendário eleitoral 2026",
        "slides": [
            "Capa.",
            "Domingo, 25 de outubro: 2º turno, das 8h às 17h (horário de Brasília).",
            "Seja quem for, nada muda na sua conta no dia 26.",
            "O boleto de novembro continua chegando no seu nome.",
            "O que depende só de você: ter uma habilidade que alguém paga pra usar.",
            "Piercing é serviço pago na hora, por procedimento, com cliente que volta pra trocar joia e fazer o próximo furo.",
            "Começa com estudo: anatomia, biossegurança, técnica, joia e preço.",
            "Vote no domingo. Invista em você hoje. Curso de Body Piercing, R$250, link na bio.",
        ],
        "legenda": "Domingo o Brasil escolhe. Segunda-feira a vida continua, com boleto e tudo.\n\nQualquer que seja o resultado, ter uma profissão na mão é decisão sua.\n\nVote. E invista em você.",
        "fontes": [
            {"t": "Movimento Econômico: data do 2º turno", "u": "https://movimentoeconomico.com.br/politica/eleicoes-2026/2026/10/04/quando-sera-o-segundo-turno-das-eleicoes-veja-a-data/"},
        ],
    },
    {
        "id": "c06", "data": "29/10", "dia": "qui", "nome": "Halloween de verdade",
        "publico": "Ambos", "impulsionar": True,
        "nota_impulso": "Pode impulsionar só sem fotos de ferida, sangue ou infecção.",
        "layout": "foto", "foto": "cena-sangue",
        "tag": "31/10", "topico": "HALLOWEEN",
        "head": "OS PIERCINGS MAIS *ASSUSTADORES* DESTE HALLOWEEN NÃO SÃO [FANTASIA.]",
        "sub": "6 erros de técnica que deixam marca pra sempre.",
        "fonte": "Conteúdo técnico · Drogasil (pistola em cartilagem)",
        "slides": [
            "Capa.",
            "Nada de sangue falso. Estes são os sustos reais de quem fura sem técnica.",
            "1. Pistola em cartilagem. O impacto machuca o tecido. Até uma grande rede de farmácia diz que o método não serve pra cartilagem.",
            "2. Joia de material errado: irritação, reação e cicatrização que não fecha.",
            "3. Posição errada: furo torto que nenhuma joia disfarça.",
            "4. Haste curta demais: com o inchaço, a joia afunda na pele.",
            "5. Esterilização de mentira: o risco que o cliente não vê.",
            "6. Pós-cuidado mal explicado: o cliente faz tudo errado em casa e a culpa cai em você.",
            "Todos esses erros se evitam com técnica. É o que o curso ensina.",
            CTA_PADRAO,
        ],
        "legenda": "O susto mais caro do Halloween não vem de fantasia. Vem de furo malfeito.\n\nSalva esse carrossel e manda pra quem está pensando em furar com qualquer um.",
        "fontes": [
            {"t": "Drogasil: furar orelha na farmácia (pistola não serve para cartilagem)", "u": "https://www.drogasil.com.br/blog/beleza/corpo/furar-orelha-na-farmacia-tudo-que-voce-precisa-saber"},
        ],
    },
    {
        "id": "c07", "data": "21/10", "dia": "qua", "nome": "R$1.741 em furos (parte 2 do salário)",
        "publico": "Iniciante", "impulsionar": False,
        "nota_impulso": "Só orgânico até o 2º turno: tema eleitoral e foto de candidato. Troque “reprodução” pelo crédito real da foto.",
        "layout": "manchete", "foto": "lula-pb-rosto",
        "tag": "PARTE 2", "topico": "2º TURNO · SALÁRIO MÍNIMO",
        "head": "O MÍNIMO DE 2027 VIROU BRIGA DE CAMPANHA. UM PIERCER FATURA *R$1.741 EM 15 FUROS.**",
        "sub": "*Exemplo: R$120 por furo, antes de joia, material e impostos.",
        "fonte": "PLOA 2027 · ago/2026 · FOTO: REPRODUÇÃO",
        "slides": [
            "Capa.",
            "Parte 2 da briga do salário. Na reta final, o mínimo virou *munição dos dois lados.*",
            "Lula defende manter a política de valorização, que leva o mínimo a *R$1.741 em 2027.* Flávio promete *preservar o valor* do piso e chama a acusação de fake news.",
            "Seja quem ganhar no dia 25, o valor final só sai em dezembro, com a inflação de novembro.",
            "Agora a conta que *nenhum dos dois* faz por você.",
            "Exemplo: furo a R$120. R$1.741 ÷ R$120 = 14,5. *Quinze furos.* Menos de 4 por semana.",
            "Isso é faturamento, não lucro. Sai joia, material descartável, espaço e impostos. E você precisa de *alvará sanitário.*",
            "No começo você fura menos. Os primeiros clientes vêm de amigos, indicação e redes.",
            "O curso custa R$250. *É o valor de uns 2 furos.*",
            CTA_PADRAO,
        ],
        "legenda": "O salário mínimo de 2027 virou briga de campanha. A proposta é R$1.741.\n\nFiz a conta de quantos furos isso dá, com os custos na mesa e sem prometer milagre.\n\nValores de exemplo; o preço do furo varia na sua cidade.",
        "fontes": [
            {"t": "Itatiaia: salário mínimo 2027, proposta de R$1.741", "u": "https://www.itatiaia.com.br/economia/salario-minimo-2027-proposta-r-1741/"},
            {"t": "A Revista: Lula x Flávio, o que pode mudar no salário mínimo", "u": "https://arevista.com.br/economia/lula-x-flavio-o-que-pode-mudar-na-aposentadoria-no-bpc-e-no-salario-minimo-apos-a-eleicao/"},
            {"t": "Portal Insights: faixa de preço por furo (fonte do setor)", "u": "https://www.portalinsights.com.br/perguntas-frequentes/quanto-um-body-piercer-ganha"},
        ],
    },
    {
        "id": "c08", "data": "06/11", "dia": "sex", "nome": "R$ 19 mil",
        "publico": "Profissional", "impulsionar": True,
        "nota_impulso": "Pode impulsionar sem nome nem foto de famosa no criativo. Os nomes ficam só nos slides orgânicos.",
        "layout": "tipo", "big": "R$19 MIL",
        "tag": "FAMOSOS", "topico": "PIERCING DE LUXO",
        "head": "É QUANTO FAMOSAS PAGAM NUM PIERCING. E VOCÊ AÍ *COBRANDO R$50* [NO FURO.]",
        "sub": "O dinheiro está no projeto da orelha, não no furo.",
        "fonte": "Uai, abr/2026 · Hello! Magazine, set/2026",
        "slides": [
            "Capa.",
            "Bruna Marquezine, Sabrina Sato e outras famosas usam piercings de ouro e diamante que chegam a R$19 mil.",
            "Em setembro, Kylie Jenner mostrou orelhas cravejadas de diamantes amarelos. No Oscar 2026, a curated ear roubou a cena.",
            "Ninguém pagou R$19 mil pelo furo. Pagou pelo projeto e pela joia.",
            "Piercer que vende só furo briga por preço com a farmácia.",
            "Piercer que vende projeto vende 3, 4, 5 pontos, joias e o retorno pra troca.",
            "Pra isso: anatomia da orelha, combinação de pontos, joia de qualidade e um orçamento bem apresentado.",
            "É isso que o profissional aprende pra parar de cobrar R$50.",
            CTA_PADRAO,
        ],
        "legenda": "Tem famosa pagando R$19 mil num piercing. E tem piercer cobrando R$50 no furo.\n\nA diferença não é o cliente. É o que você sabe vender.",
        "fontes": [
            {"t": "Uai: piercing de luxo das famosas pode chegar a R$19 mil", "u": "https://www.uai.com.br/app/entretenimento/famosos/2026/04/20/not-famosos,381438/piercing-de-luxo-das-famosas-pode-chegar-a-r-19-mil-e-tendencia-viraliza.shtml"},
            {"t": "Hello! Magazine: Kylie Jenner e os novos piercings", "u": "https://www.hellomagazine.com/us/922910/kylie-jenner-unveils-daring-new-piercing-thats-about-to-go-viral/"},
            {"t": "CNN Brasil: curated ears no Oscar 2026", "u": "https://www.cnnbrasil.com.br/lifestyle/curated-ears-roubaram-cena-no-oscar-2026-saiba-o-que-e/"},
        ],
    },
    {
        "id": "c09", "data": "10/11", "dia": "ter", "nome": "A IA não fura",
        "publico": "Iniciante", "impulsionar": True,
        "nota_impulso": "Pode impulsionar.",
        "layout": "foto", "foto": "atendimento-sangue",
        "tag": "TECNOLOGIA", "topico": "IA × TRABALHO",
        "head": "A IA ESCREVE, DESENHA E PROGRAMA. *ELA NÃO FURA* UMA [ORELHA.]",
        "sub": "Mão, anatomia e confiança: o que nenhum app entrega.",
        "fonte": "OIT · exposição de ocupações à IA generativa (2025)",
        "slides": [
            "Capa.",
            "A pergunta de 2026: “a IA vai pegar meu emprego?”",
            "O índice da OIT de 2025 mede a exposição de cada ocupação à IA generativa. No topo estão as funções de escritório, como digitação e entrada de dados.",
            "A IA escreve legenda. Não avalia anatomia, não segura uma agulha e não acalma cliente nervoso.",
            "Piercing é técnica, mão e confiança. As três coisas que um aplicativo não entrega.",
            "E a IA ainda trabalha pra você: agenda, legenda, resposta no direct. Você fica com o que dá dinheiro, o atendimento.",
            "Profissão de mão se aprende com método.",
            CTA_PADRAO,
        ],
        "legenda": "A IA já escreve, desenha e programa.\n\nAinda não inventaram app que fure uma orelha com segurança.\n\nSe você quer uma profissão que a tecnologia ajuda em vez de substituir, o curso está no link da bio.",
        "fontes": [
            {"t": "OIT, Working Paper 140: Generative AI and Jobs (2025)", "u": "https://webapps.ilo.org/static/english/intserv/working-papers/wp140/index.html"},
            {"t": "WAM: uma em cada quatro ocupações exposta à IA generativa, diz OIT", "u": "https://www.wam.ae/en/article/bjrpwru-one-four-jobs-risk-being-transformed-genai-ilo"},
        ],
    },
    {
        "id": "c10", "data": "13/11", "dia": "sex", "nome": "Umbigo no Carnaval",
        "publico": "Ambos", "impulsionar": True,
        "nota_impulso": "Melhor candidato a anúncio da campanha. Impulsione do dia 13/11 até o fim de janeiro.",
        "layout": "tipo", "big": "9 FEV",
        "tag": "CARNAVAL 2027", "topico": "CONTAGEM REGRESSIVA",
        "head": "QUEM QUER *PIERCING NO UMBIGO* NO CARNAVAL JÁ ESTÁ ATRASADO. [E VAI PROCURAR ALGUÉM AGORA.]",
        "sub": "Umbigo leva de 6 a 12 meses pra cicatrizar. A procura começa já.",
        "fonte": "Calendário Carnaval 2027 · Observatório dos Famosos, ago/2026",
        "slides": [
            "Capa.",
            "Carnaval 2027: terça, *9 de fevereiro.* O pré-carnaval já começa em 30 e 31 de janeiro.",
            "O piercing no umbigo *voltou com força* em 2026. Virginia Fonseca e Maya Massafera ajudaram a trazer de volta.",
            "Só que o umbigo leva de *6 a 12 meses* pra cicatrizar por completo.",
            "Ou seja: quem quer ir pra avenida com ele *já está atrasado.* E vai procurar um piercer nas próximas semanas.",
            "Iniciante: é a *maior janela de procura do ano* pra começar. Profissional: é hora de agenda cheia e protocolo pronto.",
            "O que esse cliente precisa ouvir: *nem todo umbigo serve,* qual joia usar e como cuidar com roupa apertada e suor no Carnaval.",
            "Quem estudar agora *atende essa fila.* Quem deixar pra janeiro vai só assistir.",
            CTA_PADRAO,
        ],
        "legenda": "Faltam menos de 90 dias pro Carnaval e o piercing no umbigo voltou.\n\nQuem quer desfilar com ele já está atrasado, e vai procurar um piercer agora.\n\nVocê vai atender essa fila ou assistir?",
        "fontes": [
            {"t": "Observatório dos Famosos: piercing no umbigo volta com força em 2026", "u": "https://observatoriodosfamosos.com.br/noticia/piercing-no-umbigo-febre-dos-anos-2000-retorna-repaginado-e-conquista-famosas"},
            {"t": "Band: quando é o Carnaval 2027", "u": "https://www.band.com.br/entretenimento/carnaval/noticias/quando-e-o-carnaval-em-2027-veja-a-data-202602081140"},
        ],
    },
    {
        "id": "c11", "data": "23/11", "dia": "seg", "nome": "Black Friday",
        "publico": "Ambos", "impulsionar": True,
        "nota_impulso": "Post de venda. Impulsione de 23 a 30/11 para quem engajou nos carrosséis anteriores.",
        "layout": "foto", "foto": "cena-noir", "cta": "LINK NA BIO",
        "tag": "27/11", "topico": "BLACK FRIDAY",
        "head": "TODO MUNDO VAI TE VENDER *DESCONTO.* EU VOU TE VENDER UMA [PROFISSÃO.]",
        "sub": "Curso de Body Piercing · iniciantes e profissionais · R$250 ou 12x",
        "fonte": "Black Friday 27/11/2026 · Cyber Monday 30/11/2026",
        "slides": [
            "Capa.",
            "Black Friday, 27 de novembro. Você vai ver desconto em celular, TV e tênis.",
            "Tudo isso perde valor no dia em que sai da caixa.",
            "Uma profissão ganha valor a cada cliente atendido.",
            "Curso de Body Piercing: do zero pra quem está começando, atualização pra quem já fura.",
            "Na Black Friday o preço continua R$250, com um bônus: [defina: aula de precificação, checklist de biossegurança ou modelo de termo de consentimento].",
            "Bônus válido até segunda, 30/11.",
            CTA_PADRAO,
        ],
        "legenda": "Black Friday é desconto em coisa que perde valor.\n\nEsse ano, compra uma coisa que ganha valor a cada cliente.\n\nCurso de Body Piercing com bônus até 30/11. Link na bio.",
        "fontes": [
            {"t": "Central do Varejo: Black Friday 2026, data", "u": "https://centraldovarejo.com.br/black-friday-2026-data-faturamento-e-preparacao-do-varejo/"},
        ],
    },
]

# Carrossel renderizado inteiro (slides internos) como exemplo de estilo
CARROSSEL_COMPLETO = ["c01", "c07", "c10"]

ANUNCIOS = [
    {"nome": "Medo", "foto": "piercer-noir",
     "texto": "Medo de machucar alguém? É o primeiro problema que o curso resolve: anatomia, marcação e protocolo antes do primeiro cliente.\n\nCurso de Body Piercing para iniciantes. R$250 ou 12x.",
     "titulo": "Do medo ao primeiro furo, com método"},
    {"nome": "Conta", "foto": None,
     "texto": "O curso custa R$250. Num exemplo de R$120 por furo, isso é o valor de uns 2 atendimentos.\n\n(Preço do furo varia por cidade. Atender exige alvará sanitário.)",
     "titulo": "R$250. Uns 2 furos."},
    {"nome": "Prova", "foto": "cena-sangue",
     "texto": "Touca, máscara, avental, descarte de perfurocortante e clorexidina na bancada. É assim que se trabalha, e é assim que você vai aprender.\n\nCurso de Body Piercing para iniciantes e profissionais.",
     "titulo": "Biossegurança não é detalhe"},
]

REELS = [
    {"gancho": "Se o seu piercer não abre a agulha na sua frente, levanta e vai embora.", "nota": "Autoridade. Pode impulsionar."},
    {"gancho": "Eu furo de touca, máscara e avental. Não é exagero, é o mínimo.", "nota": "Use o vídeo do atendimento da foto."},
    {"gancho": "3 sinais de que quem te furou não sabia o que estava fazendo.", "nota": "Educativo. Pode impulsionar."},
    {"gancho": "R$250 numa bet somem em 10 minutos. R$250 aqui viram profissão.", "nota": "Pauta quente (bets). Só orgânico: anúncio que cita aposta cai na política de jogos da Meta."},
    {"gancho": "Quanto custa montar um cantinho de piercing? Fiz a lista.", "nota": "Iniciante. Mostre custos reais, com alvará."},
]


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    data = {"carrosseis": CARROSSEIS, "completo": CARROSSEL_COMPLETO,
            "anuncios": ANUNCIOS, "reels": REELS}
    with open(os.path.join(here, "campanha.json"), "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
    print("ok", len(CARROSSEIS), "carrosséis")
